// <auto-generated />
using System;
using ClinicalEnrollmentSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicalEnrollmentSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306144456_AddRowVersion")]
    partial class AddRowVersion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicalEnrollmentSystem.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnrolledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("TrialId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("ClinicalEnrollmentSystem.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Patients_Name");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 58,
                            Condition = "Hypertension",
                            Name = "James Morrison"
                        },
                        new
                        {
                            Id = 2,
                            Age = 64,
                            Condition = "Type 2 Diabetes",
                            Name = "Sarah Al-Hassan"
                        },
                        new
                        {
                            Id = 3,
                            Age = 71,
                            Condition = "Chronic Kidney Disease",
                            Name = "Robert Chen"
                        });
                });

            modelBuilder.Entity("ClinicalEnrollmentSystem.Models.Trial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxPatients")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Trials_Status");

                    b.ToTable("Trials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxPatients = 3,
                            Status = "Active",
                            Title = "Cardiovascular Risk Study"
                        },
                        new
                        {
                            Id = 2,
                            MaxPatients = 2,
                            Status = "Active",
                            Title = "Diabetes Prevention Trial"
                        });
                });

            modelBuilder.Entity("ClinicalEnrollmentSystem.Models.Enrollment", b =>
                {
                    b.HasOne("ClinicalEnrollmentSystem.Models.Patient", "Patient")
                        .WithMany("Enrollments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicalEnrollmentSystem.Models.Trial", "Trial")
                        .WithMany("Enrollments")
                        .HasForeignKey("TrialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Trial");
                });

            modelBuilder.Entity("ClinicalEnrollmentSystem.Models.Patient", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("ClinicalEnrollmentSystem.Models.Trial", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
